### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by QuentinFchx** [koistya/gulp-csscomb#15]
CssComb 3.1.x is out [(changelog)](https://github.com/csscomb/csscomb.js/blob/master/CHANGELOG.md)
Could you please update the plugin's dependencies ?

**Comment by QuentinFchx** [comment]
@koistya, by chance, do you have the time to fix it ?
Otherwise I'll be happy to provide a PR :smile:

**Comment by koistya** [comment]
Please do :+1:

**Comment by Skoks** [comment]
#16

**Comment by QuentinFchx** [comment]
Thank you for the PR @Skoks :+1:
