### ISSUE TITLE
Allow to explicitly specify the location of the .csscomb.json file

### ISSUE THREAD

**Issue by koistya** [koistya/gulp-csscomb#4]
So, it could be used like this:

``` javascript
var csscomb = require('gulp-csscomb');

csscomb(); // will load default 'csscomb' config; or will read
           // configuration from the .csscomb.json file if it exists

var default = csscomb('csscomb'); // default config
var zen = csscomb('zen'); // one of the pre-defined configs
var yandex = csscomb('yandex'); // one of the pre-defined configs
var custom = csscomb('./config/csscomb.json'); // custom config
```

**Comment by charliegeiger89** [comment]
Is there any working example of using a .csscomb.json file in a specific directory? I cannot get this feature to work at all. I am currently using a separated task directory structure which places individual task.js files in a nested gulp directory and I would really like to keep the config file out of the project root directory. 
```
root
> gulp
    > tasks
        > development
            > csscomb.js    ( task file )
            > .csscomb.json ( config file )
```
Just as @saviomd has mentioned, both methods fail to work. 

```
gulp.task('csscomb', function(){
    gulp.src( source )
        .pipe( comb('./.csscomb.json') )
        .pipe( gulp.dest( public ) );
});
```
The only way to get the custom config file working is to place is in the project root.

**Comment by Alecto** [comment]
the  same problem - csscomb.json location doesnt work

**Comment by MrZyr0** [comment]
Hello,
I try to use this plugin with my own config file too.
 tried all ways but my config file is always ignored ...

Here it's my gulpfile :
`const gulp_csscomb = require('gulp-csscomb')

gulp.task('sass', function() {
    return gulp.src(srcSass)
    .pipe(gulp_sass())
    .pipe(gulp_csscomb('./csscomb_dev_config.json'))
    .pipe(gulp.dest(publicStyleDest));
});`


When I specify `.pipe(gulp_csscomb('zen'))` or `.pipe(gulp_csscomb('yandex'))` it tells me "Configuration file not found:" but I haven't any error when I specify my own config.
